### ISSUE TITLE
MLLP Implementation

### ISSUE THREAD

**Issue by Gehlot** [dib0/HL7Fuse#1]
Hello ,
very very thanks for this code , very useful and very clean code.
i am working on HL7 message 
i saw in this code file server and file session implement 
but i want MLLP server and session,please give me any suggestion, i want to see how to work MLLP .

Thanks,
Pramod.

**Comment by dib0** [comment]
Hi!

Thank you! Good to hear!

The MLLP server/session implementation is right there in the configuration:
<server name="HL7Fuse" serverTypeName="MLLPServer" ip="Any" port="2020" maxRequestLength="2048" maxConnectionNumber="100">

Take a look at the App.config. This shows you how to start an MLLP server. Did you read the documentation, that might be helpful too.

Please let me know if these suggestions help!

Bas
