### ISSUE TITLE
License confusion between depending libraries

### ISSUE THREAD

**Issue by woehrl01** [dib0/HL7Fuse#11]
Recently you changed the license from GPL to MIT which is awesome! But some of the depending libraries are still much more restrictive/different:
- SuperSocket: Apache 2.0
- NHapi: Mozilla Public License 2.0
- NHapiTools: GPL

Especially NHapiTools with the GPL makes HL7Fuse still not usable under MIT, which is not obvious at first sight.
As your the owner of both projects, it would be great if you could make both projects more "compatible" to each other, to reduce confusion for new users.

**Comment by dib0** [comment]
Hi,

Thanks for your comment. You are right that both my projects had a different license model. I changed NHapiTools to the MIT license!

Thanks again!

**Comment by woehrl01** [comment]
awesome! thanks for the fast response and change!
