### ISSUE TITLE
Publish as nuget package

### ISSUE THREAD

**Issue by jkiddo** [dib0/HL7Fuse#12]
Would you, @dib0 , consider publishing this project on the nuget repo?

**Comment by dib0** [comment]
Hi!

I have considered it. I already got this request from others. I'm just not really sure. The thing is that you can run HL7Fuse as a standalone application, write "plugins" to extent functionality or use it as a basis for further development.

So I would like to do provide a nuget package, but I'm unsure on the right way to go here. Any suggestions?

**Comment by jkiddo** [comment]
Okay - it depends on its purpose. I'm coming from the Java world where HAPI is the only serious implementation to use and it contains both the HL7 model and the tools for sending and receiving messages and I've been using it quite heavily and even contributed to it.

As I see it, in the .NET community, we got nHapi, which is only the model. Then you've created NHapiTools which can be used for dispatching messages, but the server part is missing. Now, the server part is contained in this project, HL7Fuse. If I was to suggest anything, it would be to let NHapiTools contain both client and server parts. Then you can depend on that in HL7Fuse and still let HL7Fuse be more like a test utility.

My understanding of your projects may not be correct, but it is how I see it.

And thank you so much for the current work. Its great to have these tools!

**Comment by dib0** [comment]
Thanks!

I'm not sure I want to integrate the both. It is true that the server part is mostly missing. You can build a server using NHapiTools (this is what I do with HL7Fuse). 

Thank you for your insights. I'll close this issue, but that doesn't mean that I'm not providing the nuget package. I'm just taking some time pondering on where both projects are going.
