### ISSUE TITLE
How to bind server to end points?

### ISSUE THREAD

**Issue by HiraveBapu** [dib0/HL7Fuse#14]
I want to add a rule that, if i receive HL7 on Port xxxx, send message YYY endpoint only. is it supported ?

**Comment by dib0** [comment]
Hi!

Yes that is certainly possible. HL7Fuse can receive messages on multiple endpoints and process them. And the send the messages to the different endpoints using routing rules. You can use the different rules to filter the messages and choose the endpoint.

Or do you want to send all the messages from xxxx to yyyy only (so recognize the incoming endpoint)? That is not possible with the standard routing rules. You could have a look at the possibility of filtering the source system (in the MSH). Of you can implement you own routing rule, but at this moment there is no information added on the source endpoint.
