### ISSUE TITLE
Sending certificate request to a client in tls mode.

### ISSUE THREAD

**Issue by JohnCrichton81** [dib0/HL7Fuse#15]
Hello,

As a tls server, I have some issues. I've got this message on the test client : "Server asked for a certificate, but list of certificate_authorities in the server response is empty"
The tls handshake is ok but I am a little bit concerned about this warning, I think it might be a problem if another client doesn't accept this empty response.
I am not a specialist and I don't understand what I am supposed to do (if it is possible with HL7Fuser/Supersocket) I found nothing in documentations...

Maybe someone had this problem.
Thanks.
Dany

**Comment by dib0** [comment]
Hi Dany,

What does your server TLS configuration look like? At firs glance it sounds like you configured a demand for a client side certificate (not just a server side certificate). In that case the server will request a certificate from the client. I think that the client is unable to provide this at the moment. If you can, please post the ssl/tls configuration of the server, so I can check.

**Comment by JohnCrichton81** [comment]
Hi, Thanks a lot for you answer.
Here is my configuration : 
```
<server name="HL7Fuse" serverTypeName="MLLPServer" ip="Any" port="22001" maxRequestLength="2048" maxConnectionNumber="100" security="tls">
	<certificate filePath="d:\1928.der"  clientCertificateRequired="true"></certificate>
      </certificate-->
<commandAssemblies>
<add assembly="HL7Fuse.Hub" />
</commandAssemblies>
</server>
```

I am using clientCertificateRequired="true", if I don't, the handshake fails but I don't know how to send a list of autorised certificate_authorities to the client in the response.

**Comment by dib0** [comment]
I see you didn't add a password. Since the server has to use a private key to encrypt/sign the data that is sent to the client (and the client uses the public key in the certificate to decrypt/validate) I think this is why the handshake fails. I never used a der file before in .Net, so I'm not really sure. The der file doesn't have to include a private key.

Is it possible for you to convert it to a pfx including the private key? Or generate a new pfx with private key? For example by using the makecert.exe tool
makecert -r -pe -n "CN=CompanyXYZ Server" -b 01/01/2007 -e 01/01/2010 -sky exchange Server.cer -sv Server.pvk
pvk2pfx.exe -pvk Server.pvk -spc Server.cer -pfx Server.pfx

And configure it like this:
<certificate filePath="localhost.pfx" password="thisistheprivatekey"></certificate>

**Comment by JohnCrichton81** [comment]
I downloaded a .p12 file on the keystore of the client. Then I installed it on my certificate store and I exported it on a pfx file with password. It contains private key.

But I have the same problem...

**Comment by dib0** [comment]
Ok, in both cases? So with client certificates enabled and without?

**Comment by JohnCrichton81** [comment]
Here is the configuration `<certificate filePath="d:\test.pfx"  clientCertificateRequired="true" password ="dany81">`

I tried different things : 

1. Without ClientCertificateRequired. Handshake fails

2. With ClientCertificateRequired Handshake ok but same warning as usual

3. Without password to be sure of the pfx file, it fails.

**Comment by dib0** [comment]
Hmmm... Did you find out what specific error is given when the handshake fails? Option 2 will give the same error, but stops now one step before that the error will occur.

Do you have the possibility to test with a different client application (just to rule out the client as a problem)

**Comment by JohnCrichton81** [comment]
Yes, I will try to find another client to do some tests. Thank you very much for your help and time.

**Comment by dib0** [comment]
No problem! Please let me know the result of the other test.

**Comment by JohnCrichton81** [comment]
Hi,
Sorry that it took some time. But I found the solution. It's a windows problem since windows 8.

As described here : [https://blogs.msdn.microsoft.com/dsnotes/2015/05/25/wcf-certificate-trust-list-ctl-issue-with-window-server-2012-r2-and-window-8-1/](url)
To fix the problem I had to add in the registry : 

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL

Value name: SendTrustedIssuerList

DWORD

Set value to 1 to re-enable sending CTL behaviors.

A reboot is required as Schannel change is kernel based and has to rely on reboot taking effect. 

Then it worked well.

Best Regards.
Dany

**Comment by dib0** [comment]
Glad that you've found the answer. Wouldn't have figured that. Lately I'm developing on Windows 10, but never ran into this before. But also didn't test windows server 2012...

Good to have the fix written down here, it will probably help others. Thank you!
