### ISSUE TITLE
HL7 Messages Not Being recieved

### ISSUE THREAD

**Issue by harmohan-jemstone** [dib0/HL7Fuse#16]
Hi 

We are currently using HL7-Fuse in one of our Projects and there is a strange thing that we are noticing right now some of the orders ORM messages are being received while others are not and there is no log of the  messages kindly drop in your email @dib0  or @jrbateman so that I can contact you regarding this issue.

Thanks & Regards
Harmohan Singh

**Comment by jrbateman** [comment]
Jrbatemanjr@gmail.com

**Comment by dib0** [comment]
bas@dib0.nl
