### ISSUE TITLE
MLLP Implementation

### ISSUE THREAD

**Issue by Gehlot** [dib0/HL7Fuse#2]
Hello
i removed file session and file server file because i want to run and check code through 
break point in mllp session and mllp server where we found error .

error is show in image

![error](https://cloud.githubusercontent.com/assets/7369177/7110820/1bf810c0-e1d5-11e4-9d30-fbd5af976c10.png)

**Comment by dib0** [comment]
Hi,

So if I understand correctly you used the standard config file provided with the solution, removed the FileServer from the configuration, then started a debugging session?

I'm not sure why it can't start the MLLPServer. Did you check the log-files to see if there is any error? The logfiles are located in {solution directory}\HL7Fuse\bin\Debug\Logs. The err.log should give a reason why this happend. 

Please let me know if there is (or isn't) any error and what the error is.

Bas

**Comment by dib0** [comment]
Reading your comments in the "Start MLLP Server and MLLP Session and Remove File Server and File Session." issue, I think this one is resolved?

I hope you find my tips in the last comment helpful for using either HL7Inspector or creating your own HL7 test-client (maybe using NHapiTools along with NHapi).
