### ISSUE TITLE
SuperSocket Dependency Issue

### ISSUE THREAD

**Issue by td48260** [dib0/HL7Fuse#26]
When I build the solution in Visual Studio 2022, I get errors due to a missing package:
  Unable to find package SuperSocket.SocketEngine with version (>= 1.6.8)

Do you know where I can find SuperSocket.SocketEngine 1.6.8?

Also, SuperSocket.Facility 1.6.8 cannot be found, but there is a 2.0.0 version.
Do I need SuperSocket.Facility 1.6.8, or will SuperSocket.Facility 2.0.0 work?

Thank you

**Comment by dib0** [comment]
Haven't touched this project for a while. Just updated the packages and it builds fine now. So if you pull the latest version the right packages will be downloaded and installed.

**Comment by td48260** [comment]
It works now. I appreciate your quick response. Thank you so much!
