### ISSUE TITLE
Start MLLP Server and MLLP Session and Remove File Server and File Session.

### ISSUE THREAD

**Issue by daminijain** [dib0/HL7Fuse#3]
Hello,
        I want to start MLLP Server and Session But 

```
public class MLLPServer : AppServer<MLLPSession, HL7RequestInfo>
{
    public MLLPServer()
        : base(new DefaultReceiveFilterFactory<MLLPBeginEndMarkReceiveFilter, HL7RequestInfo>())
    {

    }
```

in above, between curly brasses{ } no write any code to start MLLP Server ,so need to write code from end user or not
![appconfig](https://cloud.githubusercontent.com/assets/8135617/7111733/9f57416a-e1e0-11e4-9913-46c56f78ee10.png)
 and Which code is uncomment from App.config for run MLLP ,Without Run File Server?

**Comment by dib0** [comment]
Hi!

I'm not sure what you mean exactly.You don't need to add any code to the MLLPServer (also not in the constructor). The MLLP server can be used as is. It inherits from the AppServer (SuperSocket).

As you can see in the App.config a MLLP server is added and started when you run the main project (HL7Fuse). You can download the binaries and run the whole application without adding any code.Starting the server is handled by SuperSocket. So a SuperSocket service is started that will read the configuration and start the different server that are in the config (in the default provided config these are a MLLP server and a FileServer.

Did you read the documentation? That explains the solution architecture and a bit about the inner workings of HL7Fuse.

Bas

**Comment by dib0** [comment]
I see you changed the title. You can remove the fileserver by removing the following lines:

<server name="HL7FuseFile" serverTypeName="FileServer" incomingDirectory="..\..\..\Test Files\Incoming" outgoingDirectory="..\..\..\Test Files\Outgoing" backupDirectory="..\..\..\Test Files\Processed" errorDirectory="..\..\..\Test Files\Error" fileMask="*.hl7" pollTime="1000" ip="127.0.0.1" port="1000">
<commandAssemblies>
<add assembly="HL7Fuse.Hub" />
</commandAssemblies>
</server>

And (this one is optional)
<add name="FileServer" type="HL7Fuse.FileServer, HL7Fuse" />
from the ServerTypes

**Comment by daminijain** [comment]
Hello ,
         Thank u for suggestion,But when i run the application and ask three option Like: r ,i ,u.When i press r so 
![cmdscreen](https://cloud.githubusercontent.com/assets/8135617/7112309/0a95f5de-e1e6-11e4-8536-b1e9c53c10ab.png)
give above screen and HL7FuseStarted.but when i press i or u so that time screen is not hold any data and operation,so what is the meaning of Press i and u and what is the output of both.

**Comment by dib0** [comment]
Hi,

Options I and U install HL7Fuse as a Windows Service, so it can run in the background. This is useful for production situations when you want HL7Fuse to be run when the server starts and run in the background.

R is the option to run it as a console application, which is mostly useful for debugging and development.

You can also add the -r as a startup parameter (in the settings of the project file). In that case HL7Fuse doesn't ask every time, but just starts as a console application.

Bas

**Comment by Gehlot** [comment]
Thank you for reply.
But i  press -r is the option to run it as a console application and check  debugging but my break point is not hit in mllp session. and i am nothing changes in code.

**Comment by dib0** [comment]
Hi,

You're are welcome. :-) Where is your breakpoint?
The session becomes relevant/active when receiving messages. So if you use the MLLP server is starts a server that listens to a certain TCP/IP port. 
If a connection is made and a HL7 message (using the MLLP protocol) is send to the server, the message will be received and parsed. This is handled by the MLLP session.

Did you start a client (for example using HL7Inspector) to send a message to the MLLPServer?

**Comment by Gehlot** [comment]
How to start a client (for example using HL7Inspector) to send a message to the MLLPServer?
my break point is MLLP session class.

**Comment by dib0** [comment]
Hi,

Well.. that's a bit out of scope for HL7Fuse (a client isn't included). It depends on your development environment and tooling you use.

HL7Inspector (http://sourceforge.net/projects/hl7inspector, it's a Java project) is a open source tool to check/edit and/or validate HL7 messages. In the tooling menu (I believe) is an option to connect to a HL7 server and send messages to it.

Another option is to build a simple client with C#. If you create a new console application and reference my other project (NHapiTools, you can easily add it by using NuGet), you can use the NHapiTools.Base.Net.SimpleMLLPClient to connect to a server and send a message. That way you have a simple test client for sending test messages.
You can either send a string (containing a HL7 message) or send a IMessage object that was parsed using NHapi.
So if you read a message from a file (you'd have to implement that) you can parse it using NHapi or just send the string.

Please check: https://github.com/dib0/NHapiTools
or add the NHapiTools using NuGet "Install-Package NHapiTools".
