### ISSUE TITLE
How to Pass HL7 Message in IMessage and Call Execute Commond In my Application.

### ISSUE THREAD

**Issue by daminijain** [dib0/HL7Fuse#6]
"MSH|^~&|SP|SPZH|MF|INTRA|201504151627||ADT^A04||P|2.3.1|111||||+91
EVN|ADTA04
PID|01||||||15/Apr/2015 4:27:46 PM|Male||||101|||^Hindi||||123456||||Indore||111|||^^^^101
NK1|||^Brother|||||||||||||||||||||||||||||||||No
PV1||||||||||||||||||||||||||||||||||||||||||||2015-02-05
IN1||||||||||||||||||||LIC||||||||||||Yes"
This Hl7 Message which is Like string ,How to Pass in IMessage Of above String(HL7 Message)
how to call this
namespace TestApplication.V24
{
    public class MessageFactory : ICommand<MLLPSession, HL7RequestInfo>
    {
        #region Public properties
        public virtual string Name
        {
            get { return "My implementation name"; }
        }
        #endregion

```
    #region Public methods
    public void ExecuteCommand(MLLPSession session, HL7RequestInfo requestInfo)
    {
        // Do something with the HL7 message
        // requestInfo.Message
    }
    #endregion
}
```

}
 in my application.

**Comment by dib0** [comment]
The factory class must inherit the right ICommand class: : ICommand<MLLPSession, HL7RequestInfo>

HL7Fuse will call the command class if you've configured it as command assembly.

To get the string into HL7Fuse you'll have to use a client (build by you or use HL7Inspector) to connect to the HL7Fuse MLLP server and send the message.

Please refer to:
https://github.com/dib0/HL7Fuse/issues/3 and
https://github.com/dib0/HL7Fuse/issues/4

Or the documentation.
