### ISSUE TITLE
HL7 Message Pass in ICommand and Get some Error.

### ISSUE THREAD

**Issue by daminijain** [dib0/HL7Fuse#7]
I m using Hl7 Fuse in my test application and Pass HL7 message in Execute Command and got some Error.See flow of my application in below attach Picture
![hl71](https://cloud.githubusercontent.com/assets/8135617/7175209/a75333c8-e42f-11e4-8240-6033fbbfa697.png)
![hl72](https://cloud.githubusercontent.com/assets/8135617/7175210/a753cf72-e42f-11e4-9b7d-4758d7122e2e.png)
![hl73](https://cloud.githubusercontent.com/assets/8135617/7175212/a75492ea-e42f-11e4-8127-4bf30f046ad6.png)
![hl74](https://cloud.githubusercontent.com/assets/8135617/7175208/a7517bdc-e42f-11e4-8acd-6db0ad418d64.png)
![hl75](https://cloud.githubusercontent.com/assets/8135617/7175211/a7548480-e42f-11e4-813d-7084510933c6.png)
![hl76](https://cloud.githubusercontent.com/assets/8135617/7175213/a75541a4-e42f-11e4-873a-52c57eab3f61.png)
![hl78](https://cloud.githubusercontent.com/assets/8135617/7175214/a775d46e-e42f-11e4-9d6d-cdd801bf6c50.png)

 and give me some resolution.

**Comment by dib0** [comment]
I have no idea what you are trying to do here? What is it you try to accomplish?

HL7Fuse is a Windows Service, you can't use this from a webpage?!? Why are you working in a webproject?

As said before: if you just want to connect to a server (in this case a website) please don't use HL7Fuse! HL7Fuse is for receiving messages (and maybe forward them to other systems).
If you want to send messages, please use NHapiTools and the class NHapiTools.Base.Net.SimpleMLLPClient.
