### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gehlot** [dib0/HL7Fuse#8]
Hello,
I have every type solution check but not solve the following error
already start HL7fuse server

![error](https://cloud.githubusercontent.com/assets/7369177/7198290/6847e8f2-e508-11e4-94a7-8452c689755a.png)

i searched but not got a a solution so,
i have request please give me any solution .......Please 

Thanks.

**Comment by dib0** [comment]
Without your code and settings I won't be able to help you solve this problem. Do you have any way to send your VS solution in a zip-file to me?

My e-mail address in in my profile.

**Comment by Gehlot** [comment]
Hello please check code. am sending in google drive
(gdrive uri)
i have shared to your mail id xxxxx@xxxxxx.xxx
Please check a code.

# 

Dib0: Edited comment for security purposes.

**Comment by dib0** [comment]
Hi,

I have a different google account (gmail e-mail adress). I requested access on that adress. It starts with divisionb0.

Sorry for the inconvenience.

**Comment by Gehlot** [comment]
Please give me your current google mail id because i can share my code with you.

**Comment by dib0** [comment]
I did: divisionb0

Also, you should have received an email from google with my permission request

**Comment by Gehlot** [comment]
ok thanks,
I have send mail code

**Comment by jrbateman** [comment]
Hi,

I have had tremendous success with HL7fuse and I have not seen that error
before. If you will post your code, I will be glad to see if I can help.

James

On Fri, Apr 17, 2015 at 3:19 AM, Gehlot notifications@github.com wrote:

> Hello,
> I have every type solution check but not solve the following error
> already start HL7fuse server
> 
> [image: error]
> https://cloud.githubusercontent.com/assets/7369177/7198290/6847e8f2-e508-11e4-94a7-8452c689755a.png
> 
> i searched but not got a a solution so,
> i have request please give me any solution .......Please
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dib0/HL7Fuse/issues/8.

## 

Best Regards,
James Bateman

**Comment by dib0** [comment]
Hi Gehlot,

I see that you and daminijain are working on the same project. So as I answered daminijain: why are you guys working from a web project? Why do you directly call the MessageFactory.

HL7Fuse is a Windows service that runs in the background by executing an exe file. It opens a TCP/IP connection and listens for incoming connections. If it receives a message it will process the message and starts certain functionality by calling implementations of interfaces.

In your code you skip all this and go right to the middle of this process (through a webpage!) and then you get errors.  No wonder!

If we get back to the beginning, maybe I can advise you. Please tell me:
1. What does the application need to do (and use some detail in your description)?
2. What type of HL7 communication do you need?
3. Is it a webapplication or a Windows application?
4. Do you send or receive messages?
